### ISSUE TITLE
Accuracy？

### ISSUE THREAD

**Issue by fangtao365** [c-dowling/eeg_cursor_bci#38]
Hello! I have some questions. The first one is about the accuracy of this model classification. In addition, can the model be used for 2D cursor control? There is a lack of introduction documents in this project, so I have these questions.

**Comment by c-dowling** [comment]
Hello, apologies for the delay in responding. When we ran the model we achieved slightly above random performance in 1D and 2D tasks. 

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-76de7674-7fff-e844-513d-ea94823ef0f9">

Model \ Task | Left-Right | Up-Down | 2D | Overall
-- | -- | -- | -- | --
SN | 0.3929 ± 0.2783 | 0.4768 ± 0.2844 | 0.3098 ± 0.2246 | 0.3934

</b>
</body>
</html>

We developed this in 10 days for [Neuromatch Academy](https://academy.neuromatch.io/) so the model could certainly be improved upon. We used a similar model as in[ _James R Stieger et al 2021 J. Neural Eng. 18 046082_](https://iopscience.iop.org/article/10.1088/1741-2552/ac0584/meta). We simplified the task however so that our BCI only aimed to classify the subjects intent (i.e. we ignored all the data about where the cursor actually moved and instead sought to predict where the target was based on EEG recordings). This would limit the value of our model in processing real-time EEG as there are more considerations (cursor velocity, changing intent depending on cursor position etc.)
